### PR TITLE
Setup skeleton for birdhouse recipes

### PR DESCRIPTION
**Pull request by drouba**

### CODE REVIEW

**Comment by jamestjw** [comment]
@drouba Commit messages should be in the present tense and in the imperative mood, i.e. instead of saying `Added xxx` you should say `Add xxx`. If you manage to get Git working in the command line let me know, I will teach you how to alter commit messages (I'm not sure if this is possible in the GUI, I have a feeling that it isn't)

**Comment by jamestjw** [comment]
@drouba oh why did you close the pull request?

**Comment by jamestjw** [comment]
could you briefly describe what the `BirdhouseModItemInit` and `Birdhouse` classes do? just to have more context

**Comment by jamestjw** [comment]
it'd be also nice to reference the relevant jira issue in the title of the pull request by adding the task name e.g. [OLB-12312]

**Comment by drouba** [comment]
I closed it because there were a bunch of issues that I wasn't able to resolve (especially with the merging with the stuff you did for circle ci) I had to start over from the beginning. This pull request was not really relevant anymore (also it was broken)

**Pull request closed without merging**
