### PR TITLE
Added Global Tagging

### PR DESCRIPTION
**Pull request by shafiqimtiaz**
To enable spawing birdhouse using any type of plank OR logs

### CODE REVIEW

**Comment by jamestjw** [comment]
This would mean that any combination of logs and planks can be used right? i.e. the type of wood does not need to be homogenous?

**Comment by shafiqimtiaz** [comment]
Exactly, any type of 'log' or 'plank' with recipe combination can be used to spawn birdhaus

**Comment by shafiqimtiaz** [comment]
btw, can u guide me - why did my CI build fail? Couldn't debug :3

**Comment by jamestjw** [comment]
> btw, can u guide me - why did my CI build fail? Couldn't debug :3

Click on `details`, the error is elaborated in CircleCI

**Comment by jamestjw** [comment]
> Exactly, any type of 'log' or 'plank' with recipe combination can be used to spawn birdhaus

Ok but this means that in the future we wont be implementing wood type specific birdhouses right? Since any mixture of wood can be used to build birdhouses right now

**Comment by shafiqimtiaz** [comment]
the tagging generator implemented by zach, and me modifying it globally means - we can associate any set of items to spawn our birdhaus

**Comment by jamestjw** [comment]
> the tagging generator implemented by zach, and me modifying it globally means - we can associate any set of items to spawn our birdhaus

no my point is that we won't have plans to say implement something like birdhouses made of Oak will have some specific behaviour

**Comment by shafiqimtiaz** [comment]
oh no. I'm pretty sure we won't have time for that.But this tagging will ease the spawing process

**Comment by jamestjw** [comment]
> oh no. I'm pretty sure we won't have time for that.But this tagging will ease the spawing process

okay cool, because I noticed that making the wood type homogenous isn't exactly complicated (while still allowing any wood type to be used)

**Review by DevV2M — APPROVED** [review]
Everything looks great

**Review by jamestjw — APPROVED** [review]
👍 ok cool, tho the commit history looks very unusual (you might have did something you shouldn't have), anyway its cool when you merge it I recommend squashing and merging

**Pull request merged**
